### PR TITLE
pointer arithmetic tutorial

### LINKED ISSUE #25: pointer-arithmetics C tutorial
Populate C file with a tutorial and challenge.

### PR DESCRIPTION
**Pull request by RR-08**
### 2. Description
Tutorial on Pointer arithmetic in C

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by funbeedev** [comment]
@RR-08 Thanks for the PR!
The check is failing because there's some warnings that need to be fixed. See the [report here](https://github.com/inspirezonetech/TeachMeCLikeIm5/runs/4124444921?check_suite_focus=true)

**Comment by RR-08** [comment]
Fixed.

**Comment by funbeedev** [comment]
@RR-08 thanks for fixing! 
Just one more thing, can you edit the challenge to be more specific? For example, what you would like the reader to do exactly with pointer arithmetic to show their understanding. Thanks!

**Comment by funbeedev** [comment]
@RR-08 Happy to merge now! The several contributions you've made to this repo are greatly appreciated :smile:

**Pull request merged**
