### PR TITLE
Update README.md

### LINKED ISSUE #71: Update README.md file for remaining tutorial links

### PR DESCRIPTION
**Pull request by srkds**
### 2. Description
- add pointers link
- add preprocessors link

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by funbeedev** [comment]
@srkds Thanks for the PR!
The update is missing `floats.c`. Please edit to include this and check again to make sure your change includes all tutorials made so far. Thanks!

**Comment by srkds** [comment]
Hi @funbeedev,

I have updated all links, please do a review and let me know if there are any links missing.

**Comment by funbeedev** [comment]
@srkds  Looks good, thanks for that :)

**Comment by srkds** [comment]
Thankyou @funbeedev

**Pull request merged**
