### PR TITLE
Hamzabohra patch 1

### LINKED ISSUE #22: declaring-functions C tutorial
Populate C file with a tutorial and challenge.

### PR DESCRIPTION
**Pull request by hamzabohra**
### 2. Description
Added a very beginner friendly tutorial explaining how to declare functions in c language with code and comments. Added a challenge at the end with expected output.

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by hamzabohra** [comment]
issue #22 solved. 
please add hacktoberfest tag.
thankyou.

**Comment by funbeedev** [comment]
@hamzabohra  Great tutorial! Thanks for the contribution :)

**Comment by hamzabohra** [comment]
You're most welcome :)
And looking forward to contribute more!!
Thankyou.

**Comment by hamzabohra** [comment]
> @hamzabohra Great tutorial! Thanks for the contribution :)

You're most welcome :) 
And looking forward to contribute more!!
Thankyou.

**Pull request merged**
