### PR TITLE
feat: passing-arguments C tutorial

### LINKED ISSUE #23: passing-arguments C tutorial
Populate C file with a tutorial and challenge.

### PR DESCRIPTION
**Pull request by motasimmakki**
### 2. Description
Passing arguments to a function in C

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by motasimmakki** [comment]
@funbeedev @sabderemane 
Kindly have a look! 🎈

**Comment by funbeedev** [comment]
@motasimmakki Thanks for your PR.
Can you edit the challenge to describe something more specific relating to passing arguments to a function? 
Note: I've accepted the PR so it counts for hacktoberfest but please make the change requested. Thanks!

**Comment by motasimmakki** [comment]
> @motasimmakki Thanks for your PR. Can you edit the challenge to describe something more specific relating to passing arguments to a function? Note: I've accepted the PR so it counts for hacktoberfest but please make the change requested. Thanks!

Thanks for your concern, kindly have a look now! ✨

**Comment by motasimmakki** [comment]
> > @motasimmakki Thanks for your PR. Can you edit the challenge to describe something more specific relating to passing arguments to a function? Note: I've accepted the PR so it counts for hacktoberfest but please make the change requested. Thanks!
> 
> Thanks for your concern, kindly have a look now! ✨

Kindly have a look!

**Comment by funbeedev** [comment]
@motasimmakki all good :)

**Pull request merged**
